
let Data = {
    'company' : 'Kitopi',
    'companyBio' : 'This week is between the 1st of july to the 7th',
    'employees' : [ {
    'employeeName' : 'Drillion',   
    'role' :  'Dispatch',
    'pay' : '9',
    'mondayStart' : '11:00:00',
    'mondayEnd' : '23:00:00', 
    'tuesdayStart' : '00:00:00',
    'tuesdayEnd' : '00:00:00', 
    'wednesdayStart' : '11:00:00',
    'wednesdayEnd' : '23:00:00', 
    'thursdayStart' : '11:00:00',
    'thursdayEnd' : '15:00:00', 
    'fridayStart' : '00:00:00',
    'fridayEnd' : '00:00:00', 
    'saturdayStart' : '11:00:00',
    'saturdayEnd' : '23:00:00', 
    'sundayStart' : '11:00:00',
    'sundayEnd' : '15:00:00'
    },
    {
        'employeeName' : 'Kelly',
        'role' :  'Dispatch',   
        'pay' : '9',
        'mondayStart' : '00:00:00',
        'mondayEnd' : '00:00:00', 
        'tuesdayStart' : '00:00:00',
        'tuesdayEnd' : '00:00:00', 
        'wednesdayStart' : '18:00:00',
        'wednesdayEnd' : '23:00:00', 
        'thursdayStart' : '18:00:00',
        'thursdayEnd' : '23:00:00', 
        'fridayStart' : '00:00:00',
        'fridayEnd' : '00:00:00', 
        'saturdayStart' : '18:00:00',
        'saturdayEnd' : '23:00:00', 
        'sundayStart' : '18:00:00',
        'sundayEnd' : '23:00:00'
        },
        {
            'employeeName' : 'Ikrim', 
            'role' :  'Dispatch',  
            'pay' : '9',
            'mondayStart' : '11:00:00',
            'mondayEnd' : '23:00:00', 
            'tuesdayStart' : '11:00:00',
            'tuesdayEnd' : '23:00:00', 
            'wednesdayStart' : '00:00:00',
            'wednesdayEnd' : '00:00:00', 
            'thursdayStart' : '00:00:00',
            'thursdayEnd' : '00:00:00', 
            'fridayStart' : '11:00:00',
            'fridayEnd' : '23:00:00', 
            'saturdayStart' : '00:00:00',
            'saturdayEnd' : '00:00:00', 
            'sundayStart' : '00:00:00',
            'sundayEnd' : '00:00:00'
            },
            {
                'employeeName' : 'Yilli', 
                'role' :  'Dispatch',  
                'pay' : '9',
                'mondayStart' : '00:00:00',
                'mondayEnd' : '00:00:00', 
                'tuesdayStart' : '00:00:00',
                'tuesdayEnd' : '00:00:00', 
                'wednesdayStart' : '00:00:00',
                'wednesdayEnd' : '00:00:00', 
                'thursdayStart' : '00:00:00',
                'thursdayEnd' : '00:00:00', 
                'fridayStart' : '00:00:00',
                'fridayEnd' : '00:00:00', 
                'saturdayStart' : '11:00:00',
                'saturdayEnd' : '23:00:00', 
                'sundayStart' : '11:00:00',
                'sundayEnd' : '23:00:00'
                },
                {
                    'employeeName' : 'Kawsar',
                    'role' :  'Dispatch',   
                    'pay' : '9',
                    'mondayStart' : '00:00:00',
                    'mondayEnd' : '00:00:00', 
                    'tuesdayStart' : '00:00:00',
                    'tuesdayEnd' : '00:00:00', 
                    'wednesdayStart' : '00:00:00',
                    'wednesdayEnd' : '00:00:00', 
                    'thursdayStart' : '00:00:00',
                    'thursdayEnd' : '00:00:00', 
                    'fridayStart' : '00:00:00',
                    'fridayEnd' : '00:00:00', 
                    'saturdayStart' : '11:00:00',
                    'saturdayEnd' : '23:00:00', 
                    'sundayStart' : '11:00:00',
                    'sundayEnd' : '23:00:00'
                    },
                    {
                        'employeeName' : 'Saltuna', 
                        'role' :  'Dispatch',  
                        'pay' : '9',
                        'mondayStart' : '00:00:00',
                        'mondayEnd' : '00:00:00', 
                        'tuesdayStart' : '00:00:00',
                        'tuesdayEnd' : '00:00:00', 
                        'wednesdayStart' : '00:00:00',
                        'wednesdayEnd' : '00:00:00', 
                        'thursdayStart' : '00:00:00',
                        'thursdayEnd' : '00:00:00', 
                        'fridayStart' : '00:00:00',
                        'fridayEnd' : '00:00:00', 
                        'saturdayStart' : '00:00:00',
                        'saturdayEnd' : '00:00:00', 
                        'sundayStart' : '00:00:00',
                        'sundayEnd' : '00:00:00'
                        },
                        {
                            'employeeName' : 'Yasmin',
                            'role' :  'Dispatch',   
                            'pay' : '9',
                            'mondayStart' : '11:00:00',
                            'mondayEnd' : '23:00:00', 
                            'tuesdayStart' : '11:00:00',
                            'tuesdayEnd' : '23:00:00', 
                            'wednesdayStart' : '11:00:00',
                            'wednesdayEnd' : '23:00:00', 
                            'thursdayStart' : '00:00:00',
                            'thursdayEnd' : '00:00:00', 
                            'fridayStart' : '00:00:00',
                            'fridayEnd' : '00:00:00', 
                            'saturdayStart' : '18:00:00',
                            'saturdayEnd' : '23:00:00', 
                            'sundayStart' : '18:00:00',
                            'sundayEnd' : '23:00:00'
                            },
                            {
                                'employeeName' : 'Migena',
                                'role' :  'Dispatch',   
                                'pay' : '9',
                                'mondayStart' : '18:00:00',
                                'mondayEnd' : '23:00:00', 
                                'tuesdayStart' : '18:00:00',
                                'tuesdayEnd' : '23:00:00', 
                                'wednesdayStart' : '18:00:00',
                                'wednesdayEnd' : '23:00:00', 
                                'thursdayStart' : '18:00:00',
                                'thursdayEnd' : '23:00:00', 
                                'fridayStart' : '18:00:00',
                                'fridayEnd' : '23:00:00', 
                                'saturdayStart' : '14:00:00',
                                'saturdayEnd' : '23:00:00', 
                                'sundayStart' : '14:00:00',
                                'sundayEnd' : '23:00:00'
                                },
                            {
                                'employeeName' : 'David', 
                                'role' :  'Interim Team Leader',
                                'pay' : '9',
                                'mondayStart' : '00:00:00',
                                'mondayEnd' : '00:00:00', 
                                'tuesdayStart' : '00:00:00',
                                'tuesdayEnd' : '00:00:00', 
                                'wednesdayStart' : '10:30:00',
                                'wednesdayEnd' : '22:30:00', 
                                'thursdayStart' : '10:30:00',
                                'thursdayEnd' : '22:30:00', 
                                'fridayStart' : '10:30:00',
                                'fridayEnd' : '22:30:00', 
                                'saturdayStart' : '10:30:00',
                                'saturdayEnd' : '22:30:00', 
                                'sundayStart' : '10:30:00',
                                'sundayEnd' : '22:30:00'
                                },
                                {
                                    'employeeName' : 'Itamar',
                                    'role' :  'CCP',   
                                    'pay' : '9',
                                    'mondayStart' : '11:00:00',
                                    'mondayEnd' : '23:00:00', 
                                    'tuesdayStart' : '00:00:00',
                                    'tuesdayEnd' : '00:00:00', 
                                    'wednesdayStart' : '00:00:00',
                                    'wednesdayEnd' : '00:00:00', 
                                    'thursdayStart' : '17:00:00',
                                    'thursdayEnd' : '23:00:00', 
                                    'fridayStart' : '11:00:00',
                                    'fridayEnd' : '23:00:00', 
                                    'saturdayStart' : '11:00:00',
                                    'saturdayEnd' : '23:00:00', 
                                    'sundayStart' : '11:00:00',
                                    'sundayEnd' : '23:00:00'
                                    },
                                    {
                                        'employeeName' : 'Eva',
                                        'role' :  'CCP',    
                                        'pay' : '9',
                                        'mondayStart' : '10:30:00',
                                        'mondayEnd' : '17:00:00', 
                                        'tuesdayStart' : '10:30:00',
                                        'tuesdayEnd' : '15:00:00', 
                                        'wednesdayStart' : '11:00:00',
                                        'wednesdayEnd' : '23:00:00', 
                                        'thursdayStart' : '11:00:00',
                                        'thursdayEnd' : '23:00:00', 
                                        'fridayStart' : '11:00:00',
                                        'fridayEnd' : '23:00:00', 
                                        'saturdayStart' : '00:00:00',
                                        'saturdayEnd' : '00:00:00', 
                                        'sundayStart' : '11:00:00',
                                        'sundayEnd' : '20:00:00'
                                        },
                                        {
                                            'employeeName' : 'Mate',
                                            'role' :  'CCP',    
                                            'pay' : '9',
                                            'mondayStart' : '15:00:00',
                                            'mondayEnd' : '23:00:00', 
                                            'tuesdayStart' : '15:00:00',
                                            'tuesdayEnd' : '23:00:00', 
                                            'wednesdayStart' : '00:00:00',
                                            'wednesdayEnd' : '00:00:00', 
                                            'thursdayStart' : '00:00:00',
                                            'thursdayEnd' : '00:00:00', 
                                            'fridayStart' : '00:00:00',
                                            'fridayEnd' : '00:00:00', 
                                            'saturdayStart' : '00:00:00',
                                            'saturdayEnd' : '00:00:00', 
                                            'sundayStart' : '00:00:00',
                                            'sundayEnd' : '00:00:00'
                                            },
                                            {
                                            'employeeName' : 'Fahmid',
                                            'role' :  'CCP',    
                                            'pay' : '9',
                                            'mondayStart' : '00:00:00',
                                            'mondayEnd' : '00:00:00', 
                                            'tuesdayStart' : '00:00:00',
                                            'tuesdayEnd' : '00:00:00', 
                                            'wednesdayStart' : '00:00:00',
                                            'wednesdayEnd' : '00:00:00', 
                                            'thursdayStart' : '14:00:00',
                                            'thursdayEnd' : '23:00:00', 
                                            'fridayStart' : '00:00:00',
                                            'fridayEnd' : '00:00:00', 
                                            'saturdayStart' : '14:00:00',
                                            'saturdayEnd' : '23:00:00', 
                                            'sundayStart' : '14:00:00',
                                            'sundayEnd' : '23:00:00'
                                            },
                                            {
                                                'employeeName' : 'Jacob',
                                                'role' :  'CCP',    
                                                'pay' : '9',
                                                'mondayStart' : '11:00:00',
                                                'mondayEnd' : '23:00:00', 
                                                'tuesdayStart' : '11:00:00',
                                                'tuesdayEnd' : '23:00:00', 
                                                'wednesdayStart' : '00:00:00',
                                                'wednesdayEnd' : '00:00:00', 
                                                'thursdayStart' : '00:00:00',
                                                'thursdayEnd' : '00:00:00', 
                                                'fridayStart' : '00:00:00',
                                                'fridayEnd' : '00:00:00', 
                                                'saturdayStart' : '00:00:00',
                                                'saturdayEnd' : '00:00:00', 
                                                'sundayStart' : '00:00:00',
                                                'sundayEnd' : '00:00:00'
                                                },
                                                {
                                                    'employeeName' : 'Sezer',
                                                    'role' :  'CCP',    
                                                    'pay' : '9',
                                                    'mondayStart' : '00:00:00',
                                                    'mondayEnd' : '00:00:00', 
                                                    'tuesdayStart' : '14:00:00',
                                                    'tuesdayEnd' : '23:00:00', 
                                                    'wednesdayStart' : '14:00:00',
                                                    'wednesdayEnd' : '23:00:00', 
                                                    'thursdayStart' : '14:00:00',
                                                    'thursdayEnd' : '23:00:00', 
                                                    'fridayStart' : '14:00:00',
                                                    'fridayEnd' : '23:00:00', 
                                                    'saturdayStart' : '14:00:00',
                                                    'saturdayEnd' : '23:00:00', 
                                                    'sundayStart' : '00:00:00',
                                                    'sundayEnd' : '00:00:00'
                                                    },
                                ]

}


export default Data